CREATE OR REPLACE DATABASE HOTEL_BOOKING_DB;
CREATE OR REPLACE SCHEMA HOTEL_BOOKING_DB.RAW;
CREATE OR REPLACE SCHEMA HOTEL_BOOKING_DB.CURATED;
CREATE OR REPLACE WAREHOUSE HOTEL_BOOKING_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE TABLE HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW (
    HOTEL STRING,
    IS_CANCELED BOOLEAN,
    LEAD_TIME NUMBER,
    ARRIVAL_DATE_YEAR NUMBER,
    ARRIVAL_DATE_MONTH STRING,
    ARRIVAL_DATE_DAY_OF_MONTH NUMBER,
    STAYS_IN_WEEKEND_NIGHTS NUMBER,
    STAYS_IN_WEEK_NIGHTS NUMBER,
    ADULTS NUMBER,
    CHILDREN NUMBER,
    BABIES NUMBER,
    COUNTRY STRING,
    MARKET_SEGMENT STRING,
    DISTRIBUTION_CHANNEL STRING,
    IS_REPEATED_GUEST BOOLEAN,
    PREVIOUS_CANCELLATIONS NUMBER,
    PREVIOUS_BOOKINGS_NOT_CANCELED NUMBER,
    RESERVED_ROOM_TYPE STRING,
    ASSIGNED_ROOM_TYPE STRING,
    BOOKING_CHANGES NUMBER,
    DEPOSIT_TYPE STRING,
    CUSTOMER_TYPE STRING,
    ADR NUMBER(10, 2),
    REQUIRED_CAR_PARKING_SPACES NUMBER,
    TOTAL_OF_SPECIAL_REQUESTS NUMBER,
    RESERVATION_STATUS STRING,
    RESERVATION_STATUS_DATE DATE,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HOTEL_BOOKING_DB.CURATED.FACT_HOTEL_BOOKINGS (
    BOOKING_ID STRING,
    HOTEL STRING,
    IS_CANCELED BOOLEAN,
    ARRIVAL_DATE DATE,
    NIGHTS_STAY NUMBER,
    GUEST_COUNT NUMBER,
    ADR NUMBER(10, 2),
    COUNTRY STRING,
    MARKET_SEGMENT STRING,
    CUSTOMER_TYPE STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FACT_HOTEL_BOOKINGS PRIMARY KEY (BOOKING_ID)
);

CREATE OR REPLACE FILE FORMAT HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_CSV_FF
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_STAGE
    URL = 's3://replace-with-your-bucket/path/'
    FILE_FORMAT = HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_CSV_FF;

CREATE OR REPLACE PIPE HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW (
    HOTEL,
    IS_CANCELED,
    LEAD_TIME,
    ARRIVAL_DATE_YEAR,
    ARRIVAL_DATE_MONTH,
    ARRIVAL_DATE_DAY_OF_MONTH,
    STAYS_IN_WEEKEND_NIGHTS,
    STAYS_IN_WEEK_NIGHTS,
    ADULTS,
    CHILDREN,
    BABIES,
    COUNTRY,
    MARKET_SEGMENT,
    DISTRIBUTION_CHANNEL,
    IS_REPEATED_GUEST,
    PREVIOUS_CANCELLATIONS,
    PREVIOUS_BOOKINGS_NOT_CANCELED,
    RESERVED_ROOM_TYPE,
    ASSIGNED_ROOM_TYPE,
    BOOKING_CHANGES,
    DEPOSIT_TYPE,
    CUSTOMER_TYPE,
    ADR,
    REQUIRED_CAR_PARKING_SPACES,
    TOTAL_OF_SPECIAL_REQUESTS,
    RESERVATION_STATUS,
    RESERVATION_STATUS_DATE
)
FROM (
    SELECT
        $1,
        TRY_TO_BOOLEAN($2),
        TRY_TO_NUMBER($3),
        TRY_TO_NUMBER($4),
        $5,
        TRY_TO_NUMBER($6),
        TRY_TO_NUMBER($7),
        TRY_TO_NUMBER($8),
        TRY_TO_NUMBER($9),
        TRY_TO_NUMBER($10),
        TRY_TO_NUMBER($11),
        $12,
        $13,
        $14,
        TRY_TO_BOOLEAN($15),
        TRY_TO_NUMBER($16),
        TRY_TO_NUMBER($17),
        $18,
        $19,
        TRY_TO_NUMBER($20),
        $21,
        $22,
        TRY_TO_DECIMAL($23, 10, 2),
        TRY_TO_NUMBER($24),
        TRY_TO_NUMBER($25),
        $26,
        TRY_TO_DATE($27)
    FROM @HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_STAGE
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE STREAM HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW_STREAM
    ON TABLE HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW;

CREATE OR REPLACE TASK HOTEL_BOOKING_DB.CURATED.TASK_LOAD_FACT_HOTEL_BOOKINGS
    WAREHOUSE = HOTEL_BOOKING_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
MERGE INTO HOTEL_BOOKING_DB.CURATED.FACT_HOTEL_BOOKINGS T
USING (
    SELECT
        SHA2(
            CONCAT(
                COALESCE(HOTEL, ''),
                '|',
                COALESCE(TO_VARCHAR(ARRIVAL_DATE_YEAR), ''),
                '|',
                COALESCE(ARRIVAL_DATE_MONTH, ''),
                '|',
                COALESCE(TO_VARCHAR(ARRIVAL_DATE_DAY_OF_MONTH), ''),
                '|',
                COALESCE(COUNTRY, ''),
                '|',
                COALESCE(CUSTOMER_TYPE, ''),
                '|',
                COALESCE(TO_VARCHAR(INGESTED_AT), '')
            ),
            256
        ) AS BOOKING_ID,
        HOTEL,
        IS_CANCELED,
        TRY_TO_DATE(
            CONCAT(
                LPAD(TO_VARCHAR(ARRIVAL_DATE_DAY_OF_MONTH), 2, '0'),
                '-',
                ARRIVAL_DATE_MONTH,
                '-',
                TO_VARCHAR(ARRIVAL_DATE_YEAR)
            ),
            'DD-MONTH-YYYY'
        ) AS ARRIVAL_DATE,
        COALESCE(STAYS_IN_WEEKEND_NIGHTS, 0) + COALESCE(STAYS_IN_WEEK_NIGHTS, 0) AS NIGHTS_STAY,
        COALESCE(ADULTS, 0) + COALESCE(CHILDREN, 0) + COALESCE(BABIES, 0) AS GUEST_COUNT,
        ADR,
        COUNTRY,
        MARKET_SEGMENT,
        CUSTOMER_TYPE,
        CURRENT_TIMESTAMP() AS UPDATED_AT
    FROM HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) S
ON T.BOOKING_ID = S.BOOKING_ID
WHEN MATCHED THEN UPDATE SET
    T.HOTEL = S.HOTEL,
    T.IS_CANCELED = S.IS_CANCELED,
    T.ARRIVAL_DATE = S.ARRIVAL_DATE,
    T.NIGHTS_STAY = S.NIGHTS_STAY,
    T.GUEST_COUNT = S.GUEST_COUNT,
    T.ADR = S.ADR,
    T.COUNTRY = S.COUNTRY,
    T.MARKET_SEGMENT = S.MARKET_SEGMENT,
    T.CUSTOMER_TYPE = S.CUSTOMER_TYPE,
    T.UPDATED_AT = S.UPDATED_AT
WHEN NOT MATCHED THEN INSERT (
    BOOKING_ID,
    HOTEL,
    IS_CANCELED,
    ARRIVAL_DATE,
    NIGHTS_STAY,
    GUEST_COUNT,
    ADR,
    COUNTRY,
    MARKET_SEGMENT,
    CUSTOMER_TYPE,
    UPDATED_AT
) VALUES (
    S.BOOKING_ID,
    S.HOTEL,
    S.IS_CANCELED,
    S.ARRIVAL_DATE,
    S.NIGHTS_STAY,
    S.GUEST_COUNT,
    S.ADR,
    S.COUNTRY,
    S.MARKET_SEGMENT,
    S.CUSTOMER_TYPE,
    S.UPDATED_AT
);

CREATE OR REPLACE VIEW HOTEL_BOOKING_DB.CURATED.VW_BOOKING_SUMMARY AS
SELECT
    HOTEL,
    ARRIVAL_DATE,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(IFF(IS_CANCELED, 1, 0)) AS CANCELED_BOOKINGS,
    AVG(ADR) AS AVG_ADR,
    AVG(GUEST_COUNT) AS AVG_GUESTS
FROM HOTEL_BOOKING_DB.CURATED.FACT_HOTEL_BOOKINGS
GROUP BY HOTEL, ARRIVAL_DATE;
