USE DATABASE HOTEL_BOOKING_DB;

SHOW TABLES IN SCHEMA HOTEL_BOOKING_DB.RAW;
SHOW TABLES IN SCHEMA HOTEL_BOOKING_DB.CURATED;
SHOW PIPES IN SCHEMA HOTEL_BOOKING_DB.RAW;
SHOW STREAMS IN SCHEMA HOTEL_BOOKING_DB.RAW;
SHOW TASKS IN SCHEMA HOTEL_BOOKING_DB.CURATED;

SELECT COUNT(*) AS RAW_ROW_COUNT
FROM HOTEL_BOOKING_DB.RAW.HOTEL_BOOKINGS_RAW;

SELECT COUNT(*) AS CURATED_ROW_COUNT
FROM HOTEL_BOOKING_DB.CURATED.FACT_HOTEL_BOOKINGS;

SELECT *
FROM HOTEL_BOOKING_DB.CURATED.VW_BOOKING_SUMMARY
ORDER BY ARRIVAL_DATE DESC
LIMIT 20;
